### ISSUE TITLE
Running `make test` multiple times fails.

### ISSUE THREAD

**Issue by obnoxxx** [gluster/samba-integration#69]
Running `make test` or `make setup.cluster` multiple times in a row fails. Or at least sometimes fails.

There are various aspects to this. One that was mentioned in PR #68 is  because smb.conf is forcefully copied over on every run which removes `[gluster-$VOLNAME]` share section (which was automatically added by GlusterFS hook scripts) and `user.smb` volume option is not set/executed from second time onwards.

**Comment by spuiuk** [comment]
One of the problems faced was because the smbpasswd command is unable to add test users and reports io errors when writing to the tdb.

I noticed that the ctdb in this case was unhealthy. When storage1 the master node and storage0 in unhealthy state. storage0 in recovery mode checks for the sanity by attempting to grab the recovery lock expecting to fail. However it is successful in grabbing the lock which isn't expected and it goes back to retrying recovery. 

I believe that this could be down to the hook scripts called from ctdb could also be causing issues with the multiple run failures. At least one failure in my system has the ctdb stop script attempt to unmount the lock filesystem and then remove entry from fstab irrespective of the status of the unmount command. The start script then mounts the lock volume and following the success of the mount, adds the entry into fstab.

The problem is that when ctdb is running, it has a lock on the recovery lock on the lock volume. The stop scripts are unable to unmount the volume but remove the fstab entry. The start scripts then attempt to mount the volume, but fail because it is already mounted. So it doesn't create the fstab entry.

So the master node now doesn't have the fstab entry to mount the recovery lock volume.

**Comment by obnoxxx** [comment]
FYI, related: https://github.com/gluster/gluster-ansible-features/pull/43

**Comment by spuiuk** [comment]
Tested running make twice after the inclusion of the PR
https://github.com/gluster/samba-integration/pull/83

I no longer see the problem.
